version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  db:
    build: ./db
    volumes:
      - sqlite-data:/data

  frontend:
    build: ./frontend/
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/src/app
    # depends_on:
    #   - api

volumes:
  sqlite-data:
